import { EventItemList, OPTION_TYPE } from 'modules/general/general.type';
import { JobList } from 'modules/jobs/types';
import { ShowDayJob, ShowDayJobList, ShowTypes } from 'modules/Show/show.types';
import { ROLE_PRODUCTION, ROLE_DIRECTOR } from 'modules/user/types';

const episodeOne = Math.random().toString();
const episodeTwo = Math.random().toString();

export const generalOptions = [
  { id: '1', type: 'ethinicity' as OPTION_TYPE, value: 'asian', label: 'Asian', description: 'Asian' },
  { id: '2', type: 'ethinicity' as OPTION_TYPE, value: 'black', label: 'Black', description: 'Black' },
  { id: '3', type: 'ethinicity' as OPTION_TYPE, value: 'caucasin', label: 'Caucasin', description: 'Caucasin' },
  { id: '4', type: 'ethinicity' as OPTION_TYPE, value: 'eastindia', label: 'EastIndia', description: 'EastIndia' },
  { id: '5', type: 'ethinicity' as OPTION_TYPE, value: 'filipino', label: 'Filipino', description: 'Filipino' },
  {
    id: '6',
    type: 'ethinicity' as OPTION_TYPE,
    value: 'firstNation',
    label: 'FirstNation',
    description: 'FirstNation',
  },
  { id: '7', type: 'ethinicity', value: 'hispanic', label: 'Hispanic', description: 'Hispanic' },
  {
    id: '8',
    type: 'ethinicity' as OPTION_TYPE,
    value: 'middleeastern',
    label: 'MiddleEastern',
    description: 'MiddleEastern',
  },
  { id: '9', type: 'ethinicity' as OPTION_TYPE, value: 'mixed', label: 'Mixed', description: 'Mixed' },
  { id: '10', type: 'ethinicity' as OPTION_TYPE, value: 'na', label: 'NA', description: 'NA' },
  { id: '11', type: 'eyes' as OPTION_TYPE, value: 'black', label: 'Black', description: 'NA' },
  { id: '12', type: 'eyes' as OPTION_TYPE, value: 'brown', label: 'Brown', description: 'NA' },
  { id: '13', type: 'eyes' as OPTION_TYPE, value: 'blue/green', label: 'Blue/Green', description: 'NA' },
  { id: '14', type: 'eyes' as OPTION_TYPE, value: 'green', label: 'Green', description: 'NA' },
  { id: '15', type: 'eyes' as OPTION_TYPE, value: 'hazel', label: 'Hazel', description: 'NA' },
  { id: '16', type: 'hair' as OPTION_TYPE, value: 'Black', label: 'Black', description: 'NA' },
  { id: '17', type: 'hair' as OPTION_TYPE, value: 'Brown', label: 'Brown', description: 'NA' },
  { id: '18', type: 'union' as OPTION_TYPE, value: 'town1', label: 'Town-1', description: 'NA' },
  { id: '19', type: 'union' as OPTION_TYPE, value: 'town2', label: 'Town-2', description: 'NA' },
  { id: '20', type: 'gender' as OPTION_TYPE, value: 'male', label: 'Male', description: 'NA' },
  { id: '21', type: 'gender' as OPTION_TYPE, value: 'female', label: 'Female', description: 'NA' },
  { id: '21', type: 'category' as OPTION_TYPE, value: 'standin', label: 'StandIn', description: 'NA' },
  { id: '22', type: 'category' as OPTION_TYPE, value: 'background', label: 'Background', description: 'NA' },
  { id: '23', type: 'category' as OPTION_TYPE, value: 'saeperformer', label: 'SAEPerformer', description: 'NA' },
  { id: '24', type: 'category' as OPTION_TYPE, value: 'photodouble', label: 'PhotoDouble', description: 'NA' },
  {
    id: '25',
    type: 'skillLevel' as OPTION_TYPE,
    value: 'expert',
    label: 'expert',
    description: 'NA',
    icon: 'faSkiing',
  },
  {
    id: '26',
    type: 'skillLevel' as OPTION_TYPE,
    value: 'professional',
    label: 'professional',
    description: 'NA',
    icon: 'faSkiing',
  },
  {
    id: '27',
    type: 'skillLevel' as OPTION_TYPE,
    value: 'aboveaverage',
    label: 'above average',
    description: 'NA',
    icon: 'faCamera',
  },
  {
    id: '28',
    type: 'skillLevel' as OPTION_TYPE,
    value: 'avarage',
    label: 'average',
    description: 'NA',
    icon: 'faCamera',
  },
];

export default [
  { id: '1', title: 'Production1', type: ShowTypes.FILM },
  { id: '2', title: 'Production2', type: ShowTypes.SERIES },
  { id: '3', title: 'Production3', type: ShowTypes.SERIES },
  { id: '11', title: 'Production1', type: ShowTypes.FILM },
  { id: '13', title: 'Production2', type: ShowTypes.SERIES },
  { id: '12', title: 'Production3', type: ShowTypes.SERIES },
  { id: '14', title: 'Production1', type: ShowTypes.FILM },
  { id: '15', title: 'Production2', type: ShowTypes.SERIES },
  { id: '16', title: 'Production3', type: ShowTypes.SERIES },
  { id: '7', title: 'Production1', type: ShowTypes.FILM },
  { id: '09', title: 'Production2', type: ShowTypes.SERIES },
  { id: '89089', title: 'Production3', type: ShowTypes.SERIES },
  { id: '110', title: 'Production1', type: ShowTypes.FILM },
  { id: '139', title: 'Production2', type: ShowTypes.SERIES },
  {
    id: '4',
    title: 'Production4',
    type: ShowTypes.FILM,
    showWorkingDays: [
      { id: Math.random().toString(), episodeId: episodeOne, title: 'Day 1', date: '2021-03-20' },
      { id: Math.random().toString(), episodeId: episodeOne, title: 'Day 1', date: '2021-03-21' },
      { id: Math.random().toString(), episodeId: episodeOne, title: 'Day 2', date: '2021-03-22' },
    ],
  },
  {
    id: '5',
    title: 'Production5',
    type: ShowTypes.SERIES,
    episodes: [
      {
        id: episodeOne,
        episodeNo: 1,
        title: 'Episode 1',
        date: '2021-03-08',
        episodeDays: [
          { id: Math.random().toString(), episodeId: episodeOne, title: 'E1.D1', date: '2021-03-20' },
          { id: Math.random().toString(), episodeId: episodeOne, title: 'E1.D2', date: '2021-03-20' },
          { id: Math.random().toString(), episodeId: episodeOne, title: 'E1.D3', date: '2021-03-23' },
        ],
      },
      {
        id: episodeTwo,
        episodeNo: 2,
        title: 'Episode 1',
        date: '2021-03-14',
        episodeDays: [
          { id: Math.random().toString(), episodeId: episodeTwo, title: 'E2.D1', date: '2021-03-25' },
          { id: Math.random().toString(), episodeId: episodeTwo, title: 'E2.D2', date: '2021-03-26' },
        ],
      },
    ],
    users: [
      {
        id: '1',
        name: 'Lisa Doe',
        firstName: 'Lisa',
        lastName: 'Doe',
        email: 'Lisa@democode.com',
        phoneNo: '+1-785-125-5698',
        address: 'Torranto',
        unionNo: '#HNG564E',
        bgPerforme: {
          gender: 'F',
          dateOfBirth: '28',
          height: '5,11"',
          weight: '115 lbs',
          hair: 'Brown',
          eyeColor: 'Blue',
          bookingDates: [
            {
              id: '1',
              month: 'AUG',
              date: '27',
              type: '',
            },
            {
              id: '2',
              month: 'AUG',
              date: '27',
              type: '',
            },
            {
              id: '3',
              month: 'AUG',
              date: '27',
              type: '',
            },
          ],
        },
        roles: ROLE_DIRECTOR,
      },
      {
        id: '2',
        name: 'Melenia Trump',
        firstName: 'Melenia',
        lastName: 'Trump',
        email: 'Melnia@democode.com',
        phoneNo: '+1-785-125-5698',
        address: 'Torranto',
        unionNo: '#KLM412E',
        bgPerforme: {
          gender: 'F',
          dateOfBirth: '28',
          height: '5,11"',
          weight: '115 lbs',
          hair: 'Brown',
          eyeColor: 'Blue',
          bookingDates: [
            {
              id: '1',
              month: 'AUG',
              date: '27',
              type: '',
            },
            {
              id: '2',
              month: 'AUG',
              date: '27',
              type: '',
            },
            {
              id: '3',
              month: 'AUG',
              date: '27',
              type: '',
            },
          ],
        },
        roles: ROLE_PRODUCTION,
      },
    ],
  },
];

const p1 = {
  id: '1',
  name: 'Lisa Doe',
  firstName: 'Lisa',
  lastName: 'Doe',
  email: 'Lisa@democode.com',
  unionNo: '#HNG564E',
  bgPerforme: {
    gender: 'F',
    dateOfBirth: '28',
    height: '5,11"',
    weight: '115 lbs',
    hair: 'Brown',
    eyeColor: 'Blue',
    bookingDates: [
      {
        id: '1',
        month: 'AUG',
        date: '27',
        type: '',
      },
      {
        id: '2',
        month: 'AUG',
        date: '27',
        type: '',
      },
      {
        id: '3',
        month: 'AUG',
        date: '27',
        type: '',
      },
    ],
  },
};

const p2 = {
  id: '2',
  name: 'Melenia Trump',
  firstName: 'Melenia',
  lastName: 'Trump',
  email: 'Melnia@democode.com',
  unionNo: '#KLM412E',
  bgPerforme: {
    gender: 'F',
    dateOfBirth: '28',
    height: '5,11"',
    weight: '115 lbs',
    hair: 'Brown',
    eyeColor: 'Blue',
    bookingDates: [
      {
        id: '1',
        month: 'AUG',
        date: '27',
        type: '',
      },
      {
        id: '2',
        month: 'AUG',
        date: '27',
        type: '',
      },
      {
        id: '3',
        month: 'AUG',
        date: '27',
        type: '',
      },
    ],
  },
};

const p3 = {
  id: '2',
  name: 'Ashley John',
  firstName: 'Ashley',
  lastName: 'John',
  email: 'John@democode.com',
  unionNo: '#KLM612E',
  bgPerforme: {
    gender: 'F',
    dateOfBirth: '21',
    height: '5,8"',
    weight: '90 lbs',
    hair: 'Golden',
    eyeColor: 'Golden',
    bookingDates: [
      {
        id: '1',
        month: 'AUG',
        date: '27',
        type: '',
      },
      {
        id: '2',
        month: 'AUG',
        date: '27',
        type: '',
      },
      {
        id: '3',
        month: 'AUG',
        date: '27',
        type: '',
      },
    ],
  },
};
export const dummyPerformer = [p1, p2];

export const dumyPerformerList = [
  { id: '1', title: 'List name', performers: dummyPerformer },
  { id: '2', title: 'All time fav', performers: [p1, p3] },
  { id: '3', title: 'My List', performers: [p2, p3] },
];

export const dummyEmailTempalte = [
  { id: '1', title: 'Template 1', templateHtml: 'Hello, Request for new role', templateType: 'email' },
  { id: '2', title: 'Template 2', templateHtml: 'Hi, Request for new Role', templateType: 'email' },
];

const job1: ShowDayJob = {
  id: '1',
  workingDayId: '1',
  title: 'Role 2',
  description: 'Role 2 for Road scene',
  date: '2021-03-26',
  dateInNumber: new Date(2021, 3, 17).valueOf(),
  location: 'Lahore',
  minHeight: '5.2',
  maxHeight: '5.5',
  ethinicity: 'Fair',
  clothingOption: 'Modern',
  bodyRequirements: 'New',
  remarks: '',
  additionalInfo: 'Will be share later',
  createdBy: '2021-03-04',
  status: 'public',
  isActive: true,
  noOfPerformerRequired: 10,
  dates: '2021-03-04',
  isSaveForLater: false,
};

const job2: ShowDayJob = {
  id: '2',
  workingDayId: '1',
  title: 'Role 3',
  description: 'Role 3 for Shopping mall scene',
  date: '2021-03-25',
  dateInNumber: new Date(2021, 3, 16).valueOf(),
  location: 'Lahore',
  minHeight: '5.8"',
  maxHeight: '6.0"',
  ethinicity: 'caucasin',
  clothingOption: 'Bold',
  bodyRequirements: 'Smart',
  remarks: '',
  additionalInfo: 'Will be share later',
  createdBy: '2021-03-04',
  status: 'public',
  isActive: true,
  noOfPerformerRequired: 10,
  dates: '2021-03-04',
  isSaveForLater: false,
};
const job3: ShowDayJob = {
  id: '3',
  workingDayId: '1',
  title: 'Role 4 Dinner Scene',
  description: 'Role 4 Dinner Scene',
  date: '2021-03-27',
  dateInNumber: new Date(2021, 3, 15).valueOf(),
  location: 'Lahore',
  minHeight: '5.8"',
  maxHeight: '6.0"',
  ethinicity: 'Black',
  clothingOption: 'Bold',
  bodyRequirements: 'Smart',
  remarks: '',
  additionalInfo: 'Will be share later',
  createdBy: '2021-03-04',
  status: 'public',
  isActive: true,
  noOfPerformerRequired: 10,
  dates: '2021-03-04',
  isSaveForLater: false,
};

export const castingRequestData: ShowDayJobList = [job1, job2, job1, job2, job1, job1, job1, job2, job2];

export const bookingData: JobList = [
  {
    id: Math.random().toString(),
    jobId: '1',
    performerId: '1',
    status: 'booked',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 11),
    end: new Date(2021, 3, 11),
    allDay: true,
    job: job1,
  },
  {
    id: Math.random().toString(),
    jobId: '1',
    performerId: '1',
    status: 'booked',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 29),
    end: new Date(2021, 3, 29),
    allDay: true,
    job: job1,
  },
  {
    id: Math.random().toString(),
    jobId: '1',
    performerId: '1',
    status: 'booked',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 28),
    end: new Date(2021, 3, 28),
    allDay: true,
    job: job1,
  },
  {
    id: Math.random().toString(),
    jobId: '1',
    performerId: '1',
    status: 'booked',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 27),
    end: new Date(2021, 3, 27),
    allDay: true,
    job: job1,
  },
  {
    id: Math.random().toString(),
    jobId: '1',
    performerId: '1',
    status: 'booked',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 12),
    end: new Date(2021, 3, 12),
    allDay: true,
    job: job1,
  },
  {
    id: Math.random().toString(),
    jobId: '1',
    performerId: '1',
    status: 'booked',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 24),
    end: new Date(2021, 3, 24),
    allDay: true,
    job: job1,
  },
  {
    id: Math.random().toString(),
    jobId: '1',
    performerId: '1',
    status: 'booked',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 23),
    end: new Date(2021, 3, 23),
    allDay: true,
    job: job1,
  },
  {
    id: Math.random().toString(),
    jobId: '1',
    performerId: '1',
    status: 'booked',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 22),
    end: new Date(2021, 3, 22),
    allDay: true,
    job: job1,
  },
  {
    id: Math.random().toString(),
    jobId: '1',
    performerId: '1',
    status: 'booked',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 21),
    end: new Date(2021, 3, 21),
    allDay: true,
    job: job1,
  },
  {
    id: Math.random().toString(),
    jobId: '2',
    performerId: '1',
    status: 'pending',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 13),
    end: new Date(2021, 3, 13),
    allDay: true,
    job: job2,
  },
  {
    id: Math.random().toString(),
    jobId: '3',
    performerId: '1',
    status: 'pending',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 14),
    end: new Date(2021, 3, 14),
    allDay: true,
    job: job3,
  },
  {
    id: Math.random().toString(),
    jobId: '4',
    performerId: '1',
    status: 'pending',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 15),
    end: new Date(2021, 3, 15),
    allDay: true,
    job: job3,
  },
  {
    id: Math.random().toString(),
    jobId: '5',
    performerId: '1',
    status: 'pending',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 16),
    end: new Date(2021, 3, 16),
    allDay: true,
    job: job3,
  },
  {
    id: Math.random().toString(),
    jobId: '6',
    performerId: '1',
    status: 'pending',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 18),
    end: new Date(2021, 3, 18),
    allDay: true,
    job: job3,
  },
  {
    id: Math.random().toString(),
    jobId: '7',
    performerId: '1',
    status: 'pending',
    unionRate: 'HB233',
    remarks: 'No Remarks',
    start: new Date(2021, 3, 17),
    end: new Date(2021, 3, 17),
    allDay: true,
    job: job3,
  },
];

export const myEventsList: EventItemList = [
  {
    id: 0,
    title: 'All Day Event very long title',
    allDay: true,
    start: new Date(2021, 3, 25),
    end: new Date(2021, 3, 25),
    dateInNumber: new Date(2021, 3, 25).valueOf(),
    description: 'Show On',
    status: 'pending',
  },
  {
    id: 1,
    title: 'Long Event',
    start: new Date(2021, 3, 26),
    end: new Date(2021, 3, 26),
    dateInNumber: new Date(2021, 3, 26).valueOf(),
    description: 'yyyyyyyyyyyyyyyyyy',
    status: 'booked',
  },
  {
    id: 4,
    title: 'Long Event',
    start: new Date(2021, 3, 27),
    end: new Date(2021, 3, 27),
    dateInNumber: new Date(2021, 3, 27).valueOf(),
    description: 'yyyyyyyyyyyyyyyyyy',
    status: 'booked',
  },
  {
    id: 2,
    title: 'Right now Time Event',
    start: new Date(2021, 3, 24),
    end: new Date(2021, 3, 24),
    dateInNumber: new Date(2021, 2, 24).valueOf(),
    description: 'cddffffffffdfdfdfd',
    status: 'booked',
  },
];

export const dummySkills = [
  {
    id: 1,
    name: 'Acting',
    subCategories: [
      { id: 6, name: 'Comedian', parentCategory: '1' },
      { id: 7, name: 'Action', parentCategory: '1' },
      { id: 8, name: 'Romantic', parentCategory: '1' },
    ],
  },
  {
    id: 2,
    name: 'Dancing',
    subCategories: [
      { id: 9, name: 'Western', parentCategory: '2' },
      { id: 10, name: 'Asian', parentCategory: '2' },
      { id: 22, name: 'Romantic', parentCategory: '2' },
    ],
  },
  {
    id: 3,
    name: 'Musician',
    subCategories: [
      { id: 11, name: 'Gittarist', parentCategory: '3' },
      { id: 12, name: 'Drammer', parentCategory: '3' },
      { id: 13, name: 'Peano', parentCategory: '3' },
    ],
  },
  { id: 4, name: 'Cook' },
  { id: 5, name: 'Speaks Korean' },
];

export const notifications = [
  {
    id: '1',
    title: 'Update your calender',
    description: 'Lorem ipsum dolor sit amet, consectetur',
    type: 'calender',
  },
  {
    id: '2',
    title: 'Prelim Call',
    description: 'Lorem ipsum dolor sit amet, consectetur',
    type: 'prelim',
  },
  {
    id: '3',
    title: 'Final Call',
    description: 'Lorem ipsum dolor sit amet, consectetur',
    type: 'final',
  },
  {
    id: '4',
    title: 'Setting',
    description: 'Lorem ipsum dolor sit amet, consectetur',
    type: 'setting',
  },
  {
    id: '5',
    title: 'Setting Updates',
    description: 'Lorem ipsum dolor sit amet, consectetur',
    type: 'update',
  },
  {
    id: '6',
    title: 'Request Denieded',
    description: 'Lorem ipsum dolor sit amet, consectetur',
    type: 'denied',
  },
  {
    id: '7',
    title: 'Request Accepted',
    description: 'Lorem ipsum dolor sit amet, consectetur',
    type: 'accepted',
  },
  {
    id: '8',
    title: 'Request Pending',
    description: 'Lorem ipsum dolor sit amet, consectetur',
    type: 'pending',
  },
];
