import asyncActionType from 'utils/reduxActions';

export const FILTER_ACTIONS = {
  LOGIN: asyncActionType('[CASTING_PAX]LOGIN'),
  LOGIN_CALL: '[CASTING_PAX]LOGIN_CALL',
  AUTHENTICATED_USER: '[CASTING_PAX]AUTHENTICATED_USER',
  AUTH_LOGOUT_BEGIN: '[CASTING_PAX]AUTH_LOGOUT_BEGIN',
  AUTH_LOGOUT: '[CASTING_PAX]AUTH_LOGOUT',
  SIGNUP: asyncActionType('[CASTING_PAX]SIGNUP'),
  SIGNUP_CALL: '[CASTING_PAX]SIGNUP_CALL',
  REGISTER_NEW_USER: '[CASTING_PAX]REGISTER_NEW_USER',
  SIGNUP_STEP_TWO: '[CASTING_PAX]SIGNUP_STEP_TWO',
  PEROFILE_UPDATE: '[CASTING_PAX]PEROFILE_UPDATE',
  CHANGE_SELECTED_TAB: '[CASTING_PAX]CHANGE_SELECTED_TAB',
  RESET_ERROR_MESSAGE: '[CASTING_PAX]RESET_ERROR_MESSAGE',

  PROFILE_FILE_UPLOAD_BEGIN: '[CASTING_PAX]PROFILE_FILE_UPLOAD_BEGIN',
  PROFILE_FILE_UPLOAD: asyncActionType('[CASTING_PAX]PROFILE_FILE_UPLOAD'),

  ADD_TOAST_IN_LIST: '[CASTING_PAX]ADD_TOAST_IN_LIST',
  REMOVE_TOAST_IN_LIST: '[CASTING_PAX]REMOVE_TOAST_IN_LIST',

  GENERAL_SETTING: asyncActionType('[CASTING_PAX]GENERAL_SETTING'),
  GENERAL_SETTING_BEGIN: '[CASTING_PAX]GENERAL_SETTING_BEGIN',

  NOTIFICATIONS: asyncActionType('[CASTING_PAX]NOTIFICATIONS'),
  NOTIFICATIONS_BEGIN: '[CASTING_PAX]NOTIFICATIONS_BEGIN',

  SHOW_SELECTION_CHANGE: '[CASTING_PAX]SHOW_SELECTION_CHANGE',
  SET_SHOW_LISTING: '[CASTING_PAX]SET_SHOW_LISTING',
  SHOW_LISTING_API: asyncActionType('[CASTING_PAX]SHOW_LISTING_API'),
  FETCH_SHOW_LISTING_BEGIN: '[CASTING_PAX]FETCH_SHOW_LISTING_BEGIN',
  SET_SHOW_SELECTED_DATE: '[CASTING_PAX]SET_SHOW_SELECTED_DATE',
  SET_SHOW_SELECTED_DATE_BEGIN: '[CASTING_PAX]SET_SHOW_SELECTED_DATE_BEGIN',
  SET_SHOW_SELECTED_DATE_JOB: asyncActionType('[CASTING_PAX]SET_SHOW_SELECTED_DATE_JOB'),

  SET_CLEAR_SEARCH_RESULT: '[CASTING_PAXSET_CLEAR_SEARCH_RESULT',
  SET_PERFORMER_SEARCH_BEGIN: '[CATING_PAX]SET_PERFORMER_SEARCH_BEGIN',
  SET_PERFORMER_SEARCH: asyncActionType('[CATING_PAX]SET_PERFORMER_SEARCH'),

  SET_JOB_REQUEST_TO_PERFOMER_BEGIN: '[CATING_PAX]SET_JOB_REQUEST_TO_PERFOMER_BEGIN',
  SET_JOB_REQUEST_TO_PERFOMER: asyncActionType('[CATING_PAX]SET_JOB_REQUEST_TO_PERFOMER'),

  SET_CREATE_MY_PERFORMER_LIST: asyncActionType('[CASTING_PAX]SET_CREATE_MY_PERFORMER_LIST'),
  SET_CREATE_MY_PERFORMER_LIST_BEGIN: '[CASTING_PAX]SET_CREATE_MY_PERFORMER_LIST_BEGIN',

  SET_ADD_PERFOMER_IN_MY_LIST_BEGIN: '[CATING_PAX]SET_ADD_PERFOMER_IN_MY_LIST_BEGIN',
  SET_ADD_PERFOMER_IN_MY_LIST: asyncActionType('[CATING_PAX]SET_ADD_PERFOMER_IN_MY_LIST'),

  ADD_SEARCH_USER_IN_LIST: '[CASTING_PAX]ADD_SEARCH_USER_IN_LIST',
  REMOVE_SEARCH_USER_IN_LIST: '[CASTING_PAX]REMOVE_SEARCH_USER_IN_LIST',

  CREATE_SHOW: asyncActionType('[CASTING_PAX]CREATE_SHOW'),
  CREATE_SHOW_BEGIN: '[CASTING_PAX]CREATE_SHOW',
  CALL_SHOW_EDIT: '[CASTING_PAX]CALL_SHOW_EDIT',
  CALL_SHOW_DETAIL: '[CASTING_PAX]CALL_SHOW_DETAIL',

  CREATE_EMPTY_SHOW_JOB: '[CASTING_PAX]CREATE_EMPTY_SHOW_JOB',
  SET_SELETED_JOB: '[CASTING_PAX]SET_SELETED_JOB',
  SET_SHOW_DAY_JOB_LIST: '[CASTING_PAX]SET_SHOW_DAY_JOB_LIST',
  CREATE_JOB_BEGIN: '[CASTING_PAX]CREATE_JOB_BEGIN',
  CREATE_JOB: asyncActionType('[CASTING_PAX]CREATE_JOB'),
  ADD_JOB: asyncActionType('[CASTING_PAX]ADD_JOB'),

  FETCH_MY_PERFORMER_LIST: asyncActionType('[CASTING_PAX]FETCH_MY_PERFORMER_LIST'),
  FETCH_MY_PERFORMER_LIST_BEGIN: '[CASTING_PAX]FETCH_MY_PERFORMER_LIST_BEGIN',
  SET_SELECTED_PERFORMER_FOR_VIEW: '[CASTING_PAX]SET_SELECTED_PERFORMER_FOR_VIEW',

  FETCH_CASTING_REQUEST_BEGIN: '[CASTING_PAX]FETCH_CASTING_REQUEST_BEGIN',
  FETCH_CASTING_REQUEST: asyncActionType('[CASTING_PAX]FETCH_CASTING_REQUEST'),

  FETCH_BOOKING_REQUEST_BEGIN: '[CASTING_PAX]FETCH_BOOKING_REQUEST_BEGIN',
  FETCH_BOOKING_REQUEST: asyncActionType('[CASTING_PAX]FETCH_BOOKING_REQUEST'),

  FETCH_CASTING_CALL_REQUEST_BEGIN: '[CASTING_PAX]FETCH_CASTING_CALL_REQUEST_BEGIN',
  FETCH_CASTING_CALL_REQUEST: asyncActionType('[CASTING_PAX]FETCH_CALL_CASTING_REQUEST'),

  FETCH_CASTING_UPDATE_NEWS_BEGIN: '[CASTING_PAX]FETCH_CASTING_UPDATE_NEWS_BEGIN',
  FETCH_CASTING_UPDATE_NEWS: asyncActionType('[CASTING_PAX]FETCH_CASTING_UPDATE_NEWS'),

  SET_JOB_FOR_VIEW: '[CASTING_PAX]SET_JOB_FOR_VIEW',
  CLOSE_JOB_FOR_VIEW: '[CASTING_PAX]CLOSE_JOB_FOR_VIEW',

  FETCH_PERFORMER_PROFILE_BEGIN: '[CASTING_PAX]FETCH_PERFORMER_PROFILE_BEGIN',
  FETCH_PERFORMER_PROFILE: asyncActionType('[CASTING_PAX]FETCH_PERFORMER_PROFILE'),
};

export const FETCH_STATUS = {
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};

export default {
  ...FILTER_ACTIONS,
};
